### ISSUE TITLE
Controls for camera and movement are reversed during Freecam

### ISSUE THREAD

**Issue by Kairon0** [UnknownX7/Cammy#22] opened 2022-08-26 19:25 UTC
Upon entering the free cam, unless my character is sitting, the camera will aim downwards. This issue seemed to be resolved when I set the bar below Death Cam mode to 0 but then my Freecam controls were reversed.

**Comment by UnknownX7** [comment] 2022-08-27 06:19
Duplicate of #21

**Closed by UnknownX7** 2022-08-27 06:19 UTC
